{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_feature_story.TestLogin object at 0x0000022855E92CC0>\n\n    @allure.story(\"密码错误\")\n    def test_login_failure(self):\n        with allure.step(\"输入用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"输入密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n    \n    \n    \n        with allure.step(\"登陆失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:23: AssertionError"}, "steps": [{"name": "输入用户名", "status": "passed", "start": 1731589496592, "stop": 1731589496592}, {"name": "输入密码", "status": "passed", "start": 1731589496592, "stop": 1731589496592}, {"name": "登陆失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\PYPro\\Py_Td\\自动化测试框架\\test_feature_story.py\", line 23, in test_login_failure\n    assert '1' == 1\n"}, "start": 1731589496592, "stop": 1731589496592}], "attachments": [{"name": "stdout", "source": "3df7c7c9-ddee-4806-9b50-207faa0ab021-attachment.txt", "type": "text/plain"}], "start": 1731589496592, "stop": 1731589496592, "uuid": "5075a50b-3383-4aca-b58c-1103d2142362", "historyId": "a0fb827149424dbc77d431148fe9f888", "testCaseId": "a0fb827149424dbc77d431148fe9f888", "fullName": "test_feature_story.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码错误"}, {"name": "feature", "value": "登录"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "孤独二里"}, {"name": "thread", "value": "28396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}