{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:9: AssertionError"}, "description": "this test fails", "start": 1731587037748, "stop": 1731587037748, "uuid": "fe9c14f7-0d65-4ff4-bb70-8a2fd2d533c9", "historyId": "924c4ecc2b1e866f13aa32d5ad57625b", "testCaseId": "924c4ecc2b1e866f13aa32d5ad57625b", "fullName": "test_allure#test_failure", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "孤独二里"}, {"name": "thread", "value": "21836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}